### ISSUE TITLE
Exists the container in case the Test fail

### ISSUE THREAD

**Issue by rakeshnambiar** [timbru31/docker-java-node#227]
Hi @timbru31 I am using this image to run the protractor tests, however recently it's not working as expected. The container is exiting in case any single test fails with the below error.

Image name - timbru31/java-node:8

```
nodeSetup_1  | [e2e] [16:59:15] E/launcher - The element reference of <button class="sc-dxgOiQ bYGPLn" type="button"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
nodeSetup_1  | [e2e] [16:59:15] E/launcher - StaleElementReferenceError: The element reference of <button class="sc-dxgOiQ bYGPLn" type="button"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
nodeSetup_1  | [e2e]     at Object.throwDecodedError (/usr/src/script/node_modules/selenium-webdriver/lib/error.js:514:15)
nodeSetup_1  | [e2e]     at parseHttpResponse (/usr/src/script/node_modules/selenium-webdriver/lib/http.js:519:13)
nodeSetup_1  | [e2e]     at doSend.then.response (/usr/src/script/node_modules/selenium-webdriver/lib/http.js:441:30)
nodeSetup_1  | [e2e]     at process._tickCallback (internal/process/next_tick.js:68:7)
nodeSetup_1  | [e2e] From: Task: WebElement.isEnabled()
nodeSetup_1  | [e2e]     at thenableWebDriverProxy.schedule (/usr/src/script/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
nodeSetup_1  | [e2e]     at WebElement.schedule_ (/usr/src/script/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
nodeSetup_1  | [e2e]     at WebElement.isEnabled (/usr/src/script/node_modules/selenium-webdriver/lib/webdriver.js:2314:17)
nodeSetup_1  | [e2e]     at actionFn (/usr/src/script/node_modules/protractor/built/element.js:89:44)
nodeSetup_1  | [e2e]     at Array.map (<anonymous>)
nodeSetup_1  | [e2e]     at actionResults.getWebElements.then (/usr/src/script/node_modules/protractor/built/element.js:461:65)
nodeSetup_1  | [e2e]     at ManagedPromise.invokeCallback_ (/usr/src/script/node_modules/selenium-webdriver/lib/promise.js:1376:14)
nodeSetup_1  | [e2e]     at TaskQueue.execute_ (/usr/src/script/node_modules/selenium-webdriver/lib/promise.js:3084:14)
nodeSetup_1  | [e2e]     at TaskQueue.executeNext_ (/usr/src/script/node_modules/selenium-webdriver/lib/promise.js:3067:27)
nodeSetup_1  | [e2e]     at asyncRun (/usr/src/script/node_modules/selenium-webdriver/lib/promise.js:2927:27)Error
nodeSetup_1  | [e2e]     at ElementArrayFinder.applyAction_ (/usr/src/script/node_modules/protractor/built/element.js:459:27)
nodeSetup_1  | [e2e]     at ElementArrayFinder.(anonymous function).args [as isEnabled] (/usr/src/script/node_modules/protractor/built/element.js:91:29)
nodeSetup_1  | [e2e]     at ElementFinder.(anonymous function).args [as isEnabled] (/usr/src/script/node_modules/protractor/built/element.js:831:22)
nodeSetup_1  | [e2e]     at citationPage.po.goToNextStep (/usr/src/script/src/pages/citation.page.js:127:55)
nodeSetup_1  | [e2e] [16:59:15] E/launcher - Process exited with error code 199
nodeSetup_1  | [e2e] npm ERR! code ELIFECYCLE
nodeSetup_1  | [e2e] npm ERR! errno 199
nodeSetup_1  | [e2e] npm ERR! serenity-protractor-cucumber-pageobjects@1.0.0 e2e: `protractor ./protractor.conf.js`
nodeSetup_1  | [e2e] npm ERR! Exit status 199
nodeSetup_1  | [e2e] npm ERR!
nodeSetup_1  | [e2e] npm ERR! Failed at the serenity-protractor-cucumber-pageobjects@1.0.0 e2e script.
nodeSetup_1  | [e2e] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
nodeSetup_1  | [e2e]
nodeSetup_1  | [e2e] npm ERR! A complete log of this run can be found in:
nodeSetup_1  | [e2e] npm ERR!     /root/.npm/_logs/2019-03-11T16_59_15_250Z-debug.log
nodeSetup_1  | [failsafe] Script 'e2e' exited with code 199
nodeSetup_1  | [report]
```

**Comment by timbru31** [comment]
How do you start the container/the tests?  
Otherwise it’s difficult to say why the container exits.

**Comment by rakeshnambiar** [comment]
Hi @timbru31 I am using docker-compose and the command using for this container is mentioned below.

‘’’
command:
          - sh
          - '-c'
          - 'npm install-test'
‘’’

**Comment by timbru31** [comment]
Could you paste the complete docker compose file if possible? Thanks!

**Comment by timbru31** [comment]
Closing due to lack of response. If the problem persists, please ping me @rakeshnambiar
