### ISSUE TITLE
Latest failed build has pushed a failing 11-jre image to docker hub

### ISSUE THREAD

**Issue by corentinaltepe** [timbru31/docker-java-node#522]
Hi,

the latest build in Actions has failed: https://github.com/timbru31/docker-java-node/actions/runs/180731795
I believe this has caused the java-node:11-jre to fail in our CI pipeline. We use this image to build our projects.

```
/usr/bin/docker start 3788f4f4e1fd69f02d081cf990a904e36b77b829d36308bff7803117396eadab
3788f4f4e1fd69f02d081cf990a904e36b77b829d36308bff7803117396eadab
/usr/bin/docker ps --all --filter id=3788f4f4e1fd69f02d081cf990a904e36b77b829d36308bff7803117396eadab --filter status=running --no-trunc --format "{{.ID}} {{.Status}}"
3788f4f4e1fd69f02d081cf990a904e36b77b829d36308bff7803117396eadab Up Less than a second
/usr/bin/docker exec  3788f4f4e1fd69f02d081cf990a904e36b77b829d36308bff7803117396eadab sh -c "command -v bash"
Error response from daemon: Container 3788f4f4e1fd69f02d081cf990a904e36b77b829d36308bff7803117396eadab is not running
##[error]Docker exec fail with exit code 1
##[debug]System.InvalidOperationException: Docker exec fail with exit code 1
   at Microsoft.VisualStudio.Services.Agent.Worker.ContainerOperationProvider.StartContainerAsync(IExecutionContext executionContext, ContainerInfo container)
   at Microsoft.VisualStudio.Services.Agent.Worker.ContainerOperationProvider.StartContainersAsync(IExecutionContext executionContext, Object data)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtensionRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
```

I'm currently trying out other tags to see if it works any better.

Any chance we run again the build, to restore working images in Docker Hub?

**Comment by corentinaltepe** [comment]
Just tried the :latest tag, and it works properly. I'll stick to that for now.

**Comment by timbru31** [comment]
Thanks, I'll take a look.

**Comment by timbru31** [comment]
Please try again, I've rebuilt the image and it works fine for me:

<img width="861" alt="image" src="https://user-images.githubusercontent.com/838003/88380828-cc9e4600-cd94-11ea-9989-eabd444d322c.png">

**Comment by corentinaltepe** [comment]
Hi, thanks a lot for your reactivity!
Will try that out on Monday and get back to you.
